#!/bin/sh

################################
# Files that will be overridden:
#	- bashrc
#	- make.conf
#	- patches/...
#	- savedconfig/...
#	- sets/...
#
# The script will create a backup-folder 'NYXBACKUP' of the originals.
# It is due to the design of portage that I cannot put those files in distinct
# folders to prevent overriding.
# After this, you can emerge @nyx by running ./update.
#################################

if [ "$(id -u)" -ne 0 ]; then
        printf '%s\n' "Are you root? I don't think so."
        exit 1
fi

etcbu=/etc/portage/pre.nyx.backup

if [ ! -d $etcbu ]; then

mkdir $etcbu
mkdir /etc/portage/nyx.backup
cp -r /etc/portage/{bashrc,make.conf,patches,savedconfig,sets} $etcbu

rm -r /etc/portage/package.*/nyx/*
rm -r /etc/portage/env/nyx/*
rm -r /etc/portage/sets/*

rsync -aPh .portage/ /etc/portage/

chown -R root:portage /etc/portage
chmod -R 750 /etc/portage

else
        printf '%s\n' "Nyx configs are apparantly installed in /etc/portage/!"
fi

###

varbu=/var/lib/portage/pre.nyx.backup

if [ ! -d $varbu ]; then

mkdir $varbu
cp /var/lib/portage/world /var/lib/portage/world_sets $varbu
> /var/lib/portage/world
printf '%s\n' "@nyx" > /var/lib/portage/world_sets

chown root:portage /var/lib/portage/world
chmod 640 /var/lib/portage/world

mirrorselect -s5

layman -f -o https://git.cosmofox.net/nyx-overlay/plain/repository.xml -a nyx-overlay
layman -a tox-overlay

else
	printf '%s\n' "Nyx configs are apparantly installed in /var/lib/portage/!"
	printf '%s\n' "Did you mean to run ./update?"
fi
