#!/bin/mksh

################################
# This script puts the freshly 
# pulled configs and tools
# in place and starts an
# update routine with portage.
#################################

git pull || exit 1

if [ -d /etc/portage/NYXupdateBACKUP ]; then

cp -r /etc/portage/{bashrc,make.conf,patches,savedconfig,sets} /etc/portage/NYXupdateBACKUP

rm -r /etc/portage/package.*/nyx/*
rm -r /etc/portage/env/nyx/*

rsync -aPh portage/ /etc/portage/

chown -R root:portage /etc/portage
chmod -R 750 /etc/portage

chown root:portage /var/lib/portage/world
chmod 640 /var/lib/portage/world

grep GENTOO_MIRRORS /etc/portage/NYXupdateBACKUP/make.conf >> /etc/portage/make.conf

overrides=$(</etc/portage/overrides.conf) ; print $overrides >> /etc/portage/make.conf

printf "\nDo you wish to sync the repos?\n"
select yn in "Yes" "No"; do
    case $yn in
        [Yy]* ) ((layman -S ; emerge-webrsync) && eix-update) || (printf "\nerror updating repos, aborting\n" ; exit 1) ;;
        [Nn]* ) printf "\nRepos not updated.\n" ; break ;;
        * ) printf "\nPlease answer y or n.\n";;
    esac ;
done

( emerge -uavG sys-apps/portage \
  && emerge --quiet-build -uavDNG @nyx @system @live-rebuild \
     && dispatch-conf \
        && env-update && source /etc/profile \
) \
&& ( emerge --depclean \
     && emerge --quiet-build -avG @preserved-rebuild \
        &&  env-update && source /etc/profile \
   ) \
   && ( eclean distfiles \
        ; emaint --check world \
        ; glsa-check -t all \
        ; makewhatis -u \
      )

else
	print 'Seems you haven't run sh install first.'
	print 'You should do that.'
fi
